version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time-tracker
    ports:
      - 9090:8080
      - 3000:3000
    volumes:
      - ./:/var/www
